In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
for i in range(len(a)):
    print(a[i])

1
2
3
4
5
6


In [9]:
# Like the original list, the array is mutable.

In [1]:
# Also like the original list, Python slice notation can be used for indexing

In [7]:
a[:3]

array([1, 2, 3])

One magor difference is that slice indexing of a `list` copies the elements into a **new list**, but slicing an `array` returns a **`view`**: an object that refers to the data in the original array.

Python List: When you slice a list, it creates a **new, independent copy** of the data.
means:
# The new list(created by slicing) **contains the same elements** as the original.
# But it is stored **in a different place in the memory**, and
# Changing the sliced list does NOT affect the original list.

In [10]:
# Slicing of a list

In [12]:
list1 = (lambda num : list(int(input(f"Enter the {i+1} element of the list: ")) for i in range(num)))(int(input("Enter the number of elements in the list : ")))

Enter the number of elements in the list :  5
Enter the 1 element of the list:  1
Enter the 2 element of the list:  2
Enter the 3 element of the list:  3
Enter the 4 element of the list:  4
Enter the 5 element of the list:  5


In [13]:
list1

[1, 2, 3, 4, 5]

In [14]:
sliced_list = list1[:3]


In [15]:
sliced_list

[1, 2, 3]

In [16]:
sliced_list[0] = 999

In [18]:
list1

[1, 2, 3, 4, 5]

In [19]:
sliced_list

[999, 2, 3]

In [20]:
# Slicing of a Array

In [26]:
arr = np.ones(4, dtype=int)


In [27]:
arr

array([1, 1, 1, 1])

In [28]:
sliced_arr = arr[:3]

In [29]:
sliced_arr

array([1, 1, 1])

In [31]:
sliced_arr[0] = 997

In [32]:
arr 

array([997,   1,   1,   1])

In [33]:
# Sliced_arr changed the value of original_arr

In [34]:
# Initializing higher dimensional arrays

In [37]:
row = int(input("Enter the numner of lists : "))

Enter the numner of lists :  3


In [39]:
col = int(input("Enter the number of elements in each list : "))

Enter the number of elements in each list :  3


In [47]:
arr = np.array((lambda row, col : list(list(int(input(f"Enter the {i+1} col and {j+1} row value: ")) for i in range(col)) for j in range(row)))(row, col))

Enter the 1 col and 1 row value:  5
Enter the 2 col and 1 row value:  5
Enter the 3 col and 1 row value:  5
Enter the 1 col and 2 row value:  5
Enter the 2 col and 2 row value:  5
Enter the 3 col and 2 row value:  5
Enter the 1 col and 3 row value:  5
Enter the 2 col and 3 row value:  5
Enter the 3 col and 3 row value:  5


In [48]:
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In NumPy, a dimension of an array is sometimes referred to as an "axis".


In [49]:
# Priniting all elements

for i in range(row):
    for j in range(col):
        print(arr[i, j])

5
5
5
5
5
5
5
5
5


# Unlike a list of lists where you'd write list[i][j], numpy allows arr[i, j]


# Axis = 0 => row wise => refers to vertical direction => operation will be performed row wise (no operation column wise) => (for example, add lists)

# Axis = 1 => operation within seperate lists. Axis refers to column wise operation. Horrizontal direction(columns). Axis 1 refers to horrizontal direction.

# In case of three dimensions,

# axis = 0 is depth (stacked layers)
# axis = 1 is rows 
# axis = 2 is columns

In [50]:
# In NumPy, what does axis = 0 represent when working with a 2D arrays ?

arr = np.array([[2,4], [6,8]])

In [51]:
arr

array([[2, 4],
       [6, 8]])

In [52]:
np.sum(arr, axis=1)

array([ 6, 14])

In [57]:
# How does axes differ when working with a 3D array compared to a 2D array?

# Think of axes as dimensions, and each additional dimensions adds a level of nesting.

# 2D Array (shape: (rows, columns))

In [91]:
# Example
row = int(input("Enter the number of lists : "))
col = int(input("Enter the number of elements in each list : "))
arr = np.array((lambda row, col : list(list(int(input(f"Enter the {j+1} row and {i+1} column element: ")) for i in range(col)) for j in range(row)))(row, col))

Enter the number of lists :  2
Enter the number of elements in each list :  3
Enter the 1 row and 1 column element:  1
Enter the 1 row and 2 column element:  2
Enter the 1 row and 3 column element:  3
Enter the 2 row and 1 column element:  4
Enter the 2 row and 2 column element:  5
Enter the 2 row and 3 column element:  6


In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
type(arr)

numpy.ndarray

In [93]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [94]:
np.sum(arr, axis=1)

array([ 6, 15])

In [95]:
# 3D Array
# Think of this is as a stack of 2D matrices

In [102]:
row = int(input("Enter the number of elements in the row : "))
col = int(input("Enter the number of elements in the column : "))
depth = int(input("Enter the number of flights : "))
three_dimensional_array = np.array((lambda row, col, depth : list(list(list(int(input(f"Enter the {k+1} flight, {j+1} row and {i+1} column element : ")) for i in range(col)) for j in range(row)) for k in range(depth)))(row, col, depth))

Enter the number of elements in the row :  2
Enter the number of elements in the column :  2
Enter the number of flights :  2
Enter the 1 flight, 1 row and 1 column element :  1
Enter the 1 flight, 1 row and 2 column element :  2
Enter the 1 flight, 2 row and 1 column element :  3
Enter the 1 flight, 2 row and 2 column element :  4
Enter the 2 flight, 1 row and 1 column element :  5
Enter the 2 flight, 1 row and 2 column element :  6
Enter the 2 flight, 2 row and 1 column element :  7
Enter the 2 flight, 2 row and 2 column element :  8


In [103]:
three_dimensional_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])